### PR TITLE
handle all rotation angles

### PR DESCRIPTION
**Pull request by abde0103**
With the few changes I made, easyocr is now able to handle any rotation angle, not only 90 multiples and any length of "rotation_info" list in the "readtext" function.

### CODE REVIEW

**Comment by Jalmoru** [comment]
Did you try it in a straight texted image? It shouldn't be giving mirror-imaged texts or something but plain text.

**Comment by cs19469** [comment]
Hello, I want to detect the numbers in the picture, but it still can't be detected after rotation. Is there any problem with my usage?
result = reader.readtext(img1, rotation_info=[-10, 10, 20, 30, 45])

**Comment by abde0103** [comment]
> Hello, I want to detect the numbers in the picture, but it still can't be detected after rotation. Is there any problem with my usage? result = reader.readtext(img1, rotation_info=[-10, 10, 20, 30, 45]) 

Nothing is wrong with your usage. The current version tests you different rotation angles and chooses the optimal one : the one which maximizes the prediction confidence, so the returned character detection will be done on one rotation angle which corresponds to the best one. In your case, you will not be able to read all the characters because they are slanted at different angles.

**Comment by RoelofKuipers** [comment]
Hello, would there be a way to solve this? I want to read the texts of all the objects in my fridge. They are in different angles. Unfortunately, therefore EasyOCR can't be used because of this issue. 
Screenshot 2022-11-21 at 15 05 05

**Pull request merged**
