### PR TITLE
Make server that users can experience easyocr in webpage!

### PR DESCRIPTION
**Pull request by Wook-2**
Hi! I'm a student who work in common computer as intern.
recently I'm working for deploying any useful and interesting project by using Ainize.
and I ainize easyocr project so that every user can experience easyocr easy!
Try click ainize button or visit webpage!  you can try it by click ainize button or [web page] link in README.md thank you!

(Ainize is a project that can deploy server for free & able to access live services from Github with one click!
if you interested in Ainize, try visit ainize.ai !)

Have a good day 😄!

### CODE REVIEW

**Comment by rkcosmos** [comment]
Do you have GPU on this server? What's the advantage over Google's colab?

**Comment by Wook-2** [comment]
Thanks for your reply!
Ainize is platform/hosting service that has multiple GPUs on its server (unlimited edition). There isn't a specific period during which your account has access to the GPU. Your program can run on it permanently (as opposed to Google Colab).
Furthermore, its deployment process is very convenient.

**Comment by Wook-2** [comment]
Well, speaking of it, I felt like I was promoting Ainize.
However, my main purpose is not to promote Ainize, but to contribute to this project by creating servers so that more people can easily experience Easyocr.

**Comment by rkcosmos** [comment]
Let's do it like this. You can help me create a server on Ainize and give me a link to this server. I'll create a section on Readme with links to all demos (colab, docker, ainize, etc). The reason I want it this way is because the library is constantly evolving and I don't have enough energy to personally update all the demos.

**Comment by rkcosmos** [comment]
You can also host Ainize's setup files on your own repository. If the demo works well, I can also give a link to your repo.

**Comment by Wook-2** [comment]
thanks then I'll give you a link of server.
just copy & paste below to README
1. [Run on Ainize](https://ainize.web.app/redirect?git_repo=github.com/Wook-2/EasyOCR)
for using API and

2. https://easyocrgpu-wook-2.endpoint.ainize.ai/
for visiting webpage

**Comment by rkcosmos** [comment]
Looks very nice, added to Readme

**Comment by rkcosmos** [comment]
By the way, can you also show version on the website? Version is going to change in the future, people should know which version are they testing.

**Comment by Wook-2** [comment]
Sure, Should I write ver 1.1 next to the title?

**Comment by rkcosmos** [comment]
something like that, I don't know which version did you installed on server. It can be shown with

```
import easyocr
print(easyocr.__version__)
```

**Comment by Wook-2** [comment]
thanks, I check my version is running on 1.1.5
스크린샷 2020-07-27 오후 5 00 26
and add version under title just like this!
스크린샷 2020-07-27 오후 5 27 52

**Comment by rkcosmos** [comment]
perfect

**Pull request closed without merging**
