### PR TITLE
Update wordbeamsearch

### LINKED ISSUE #267: 10x speed improvement in WordBeamSearch Decoding
Hi EasyOCR team !

Thanks for open-sourcing the OCR tool. I have been working and customizing it for my use case for sometime now.
Recently while doing latency testing, I found that the ```wordbeamsearch``` decoding method takes a lot of time(infact more than the forward pass on cpu)

On digging deep the issue I found was with the use of ```simplify_label`` function 
here : https://github.com/JaidedAI/EasyOCR/blob/8af936ba1b2f3c230968dc1022d0cd3e9ca1efbb/easyocr/utils.py#L118

If you check line L169 & L189 , in utils.py, the function simplify_label is called ~ (168+5) times at every time-step.
I have done some modifications and wrote a competitive version for simplify label which is giving me 10x better performance on the decoding.

Can you please let me know, is there any particular for format in which I can give a PR for this ?

### PR DESCRIPTION
**Pull request by amitbcp**
fix #267 
This PR introduces a conditional check to reduce & optimize the number of calls made to simplify_label which is a memory intensive call.

```fast_simplify_label``` is introduced that handles most of the cases of ```simplify_label``` with a conditional check and is faster. As a fallback ```simplify_label``` is used.

### CODE REVIEW

**Comment by amitbcp** [comment]
@rkcosmos I have some Test-Cases as well. Can you please point me to the other testcases with which I can place these ?

**Comment by rkcosmos** [comment]
I tested your code and it produced error. Pls see line 261-266, there's an error because output format of `sort` method is changed and later use of that method is not updated accordingly. I think it's possible to retain old format so we don't have to change later code.

**Comment by amitbcp** [comment]
@rkcosmos Thanks for the comment. I reverted back the format of ```sort``` method so that no other places break in future. In my use case Line 261-266 is stripped out , so never faced this issue.
Please have a look at the updated PR.

**Comment by rkcosmos** [comment]
Merged, thanks for your contribution.

**Pull request merged**
