### PR TITLE
Correct Vietnameses characters

### PR DESCRIPTION
**Pull request by t-tran**
Remove non-Vietnamese characters
Add missing ones.

A good reference: https://en.wikipedia.org/wiki/Vietnamese_alphabet

### CODE REVIEW

**Comment by rkcosmos** [comment]
Wow, that's a lot of missing characters. I usually scrape  a lot of vi.wikipedia pages and count character frequency. Those missing chars are rarely seen there. Are the missing ones used less frequent than others or it is just wikipedia?

**Comment by Gaarv** [comment]
I can concur on this. To answer the question those are used everyday, vietnamese is a tonal language, hence the many differents symbols.

**Comment by rkcosmos** [comment]
I see, that's probably the reason why Google vision build a separate model for Viet. Where can I find word list that use those characters? Can you guys help update it?

**Comment by t-tran** [comment]
@rkcosmos You can scrape newspapers in Vietnamese such as BBC Vietnamese: https://www.bbc.com/vietnamese or https://www.who.int/vietnam/vi/news

**Pull request merged**
