### PR TITLE
 Allow loading URL in .readtext(url), issue #86

### PR DESCRIPTION
**Pull request by korakot**
I already test that it really works this time.

### CODE REVIEW

**Comment by rkcosmos** [comment]
Do we still need to change 'loadImage' function?

**Comment by korakot** [comment]
No. The `loadImage()` can work with URL already. Only `cv2.imread()` need a local file.

**Comment by rkcosmos** [comment]
I tested it and got this error

ValueError: Could not find a format to read the specified file in mode 'i'

**Comment by rkcosmos** [comment]
```
ValueError                                Traceback (most recent call last)
<ipython-input-5-09aa17089c09> in <module>
----> 1 result = read.readtext('https://github.com/JaidedAI/EasyOCR/blob/master/examples/english.png', decoder = 'greedy')
      2 result

~/anaconda3/lib/python3.7/site-packages/easyocr/easyocr.py in readtext(self, image, decoder, beamWidth, batch_size, contrast_ths, adjust_contrast, filter_ths, workers, whitelist, blacklist)
    205 
    206         if type(image) == str:
--> 207             img = loadImage(image)
    208             if image.startswith('http://') or image.startswith('https://'):
    209                 tmp, _ = urllib.request.urlretrieve(image)

~/anaconda3/lib/python3.7/site-packages/easyocr/imgproc.py in loadImage(img_file)
     10 
     11 def loadImage(img_file):
---> 12     img = io.imread(img_file)           # RGB order
     13     if img.shape[0] == 2: img = img[0]
     14     if len(img.shape) == 2 : img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

~/anaconda3/lib/python3.7/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, flatten, **plugin_args)
     59 
     60     with file_or_url_context(fname) as fname:
---> 61         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     62 
     63     if not hasattr(img, 'ndim'):

~/anaconda3/lib/python3.7/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    208                                (plugin, kind))
    209 
--> 210     return func(*args, **kwargs)
    211 
    212 

~/anaconda3/lib/python3.7/site-packages/imageio/core/functions.py in imread(uri, format, **kwargs)
    262 
    263     # Get reader and read first
--> 264     reader = read(uri, format, "i", **kwargs)
    265     with reader:
    266         return reader.get_data(0)

~/anaconda3/lib/python3.7/site-packages/imageio/core/functions.py in get_reader(uri, format, mode, **kwargs)
    180     if format is None:
    181         raise ValueError(
--> 182             "Could not find a format to read the specified file " "in mode %r" % mode
    183         )
    184 

ValueError: Could not find a format to read the specified file in mode 'i'
```

**Comment by korakot** [comment]
Don't use `blob`, use `raw` to get the real image.

    https://github.com/JaidedAI/EasyOCR/raw/master/examples/english.png

**Pull request merged**
