### PR TITLE
Estimate number of characters in textbox

### PR DESCRIPTION
**Pull request by adamfrees**
This PR introduces the ability to estimate the number of characters in each textbox, first mentioned in Issue #311 .  It adds the optional argument `optimal_num_chars` to the `detect` function, which represents the optimal number of characters in each text box.

The output of the `detect` function remains a list of text boxes. However, if for example a user is looking for a 10-digit serial number, setting `optimal_num_chars=10` will estimate the number of characters in each text box, and sort the output such that text boxes with around 10 characters are put first. This way, when the user loops through this list calling `predict` on each textbox, they are able to find the desired e.g. serial number quickly.

As I mentioned in the issue, I found this useful in my case - happy to make any changes to improve it / make the approach more general!

### CODE REVIEW

**Comment by rkcosmos** [comment]
Thanks, your code looks pretty neat. I will review and feedback soon.

**Comment by rkcosmos** [comment]
Here is an error when I try to run your code. 

Screenshot from 2020-12-06 14-42-37

**Comment by adamfrees** [comment]
Hello, thanks for catching this - should be fixed now!

**Comment by rkcosmos** [comment]
perfect, thanks for your contribution!

**Comment by rkcosmos** [comment]
will add this to documentation soon.

**Pull request merged**
