### PR TITLE
Serbian language (cyrillic and latin)

### PR DESCRIPTION
**Pull request by milosjovac**
Added:

- easyocr/character/rs_latin_char.txt
- easyocr/character/rs_cyrilic_char.txt
- easyocr/dict/rs_latin.txt
- easyocr/dict/rs_cyrilic.txt

Dictionaries are copied from [LibreOffice Spelling and Hyphenation
extension package for Serbian (Cyrillic and Latin)](https://github.com/grakic/dict-sr-oxt).

### CODE REVIEW

**Comment by rkcosmos** [comment]
2 set? Is it similar to Chinese has simplified/traditional version?

**Comment by milosjovac** [comment]
It's a bit different. Serbian language can be written in 2 alphabets equally (also known as digraphia). You can find more about this topic [on Wikipedia](https://en.wikipedia.org/wiki/Romanization_of_Serbian#:~:text=Serbian%20is%20written%20in%20two,is%20an%20example%20of%20digraphia.).

Fun fact: If you give an article to Serbian people to read, and then hide it, they will have a hard time remembering was it in Latin or Cyrillic. 😀

**Comment by rkcosmos** [comment]
Why is there 'Dž' when you have both 'D' and 'ž'?

**Comment by milosjovac** [comment]
They are separate letters:
- D - **/d/** 
- Dž - **/d͡ʒ/** (considered single letter)
- L - **/l/**
- Lj - **/ʎ/** (considered single letter)
- N - **/n/**
- Nj - **/ɲ/**

D and Ž, L and J, and N and J are never neighbor characters separately. They form a single character/voice when written together. Is this going to mess up the algorithm? Maybe it's not relevant for a character recognition?

**Comment by rkcosmos** [comment]
From algorithm (character level) point of view, I think we can ignore the existence of single letter 'Dž'. If OCR see something like 'abcDžefg', then it will just say there are 8 characters. Does that sound ok?

However if I have to build language model later, then it would matter to treat 'Dž' or 'Nj' as one character.

**Comment by milosjovac** [comment]
Yes, that sounds ok.

**Comment by milosjovac** [comment]
Should I create a new PR?

**Comment by rkcosmos** [comment]
Not necessary, I will take care of it.

**Comment by kmilos** [comment]
Please change the language tags to ISO 639 "sr" asap, as "rs" is not a recognized tag for the Serbian language by any software platform out there.

I would also recommend switching to [BCP47 ](https://en.wikipedia.org/wiki/IETF_language_tag) compliant tags for your whole project, not only Serbian.

In this case "sr_Cyrl" (or even just "sr" as _Cyrl is implied) and "sr_Latn" (should be w/ "-", but underscore is also ok as used by [CLDR](http://cldr.unicode.org/)).

https://unicode-org.github.io/cldr-staging/charts/latest/summary/sr.html
https://unicode-org.github.io/cldr-staging/charts/latest/summary/sr_Latn.html

**Pull request merged**
