### PR TITLE
Adding the Arabic Language

### PR DESCRIPTION
**Pull request by MohamedAliRashad**
We can track the addition of new words or correction of previous ones here

### CODE REVIEW

**Comment by iMrDJAi** [comment]
I suggest to pick Arabic chars from [here](https://en.wikipedia.org/wiki/Arabic_script_in_Unicode).
The given chars list is uncompleted.

**Comment by MohamedAliRashad** [comment]
@iMrDJAi I sticked to the original 28 characters, i don't know if the other formats will give better results or not actually.

**Comment by rkcosmos** [comment]
Generally criteria would be 'Are additional characters widely used in normal situation?'. If yes, then add it. I cannot read Arabic so I really have no idea.

**Comment by MohamedAliRashad** [comment]
@rkcosmos The thing about arabic characters is that it can take different shapes based on the context it is in ... Take this photo for example
Screenshot from 2020-07-10 06-29-05
The leftmost column is the base characters in the language, the last three columns has to do with how the character will look like if it was linked with other characters in a word.

You can see that they are very similar, so i don't know if it will be better for CRAFT to include them or not.

**Pull request merged**
