### PR TITLE
Adding Telugu language support

### PR DESCRIPTION
**Pull request by Msrikrishna**
Exhaustive Telugu character combinations along with 1000 most frequently used words are added

### CODE REVIEW

**Comment by rkcosmos** [comment]
Your language has >2000 characters? Why does Wikipedia say 'The Telugu script is an abugida consisting of 60 symbols — 16 vowels, 3 vowel modifiers, and 41 consonants.'?

**Comment by Msrikrishna** [comment]
We have about 60 vowels+ consonants(basic characters). Additionally, we have consonant+ consonant combinations and vowel+ consonant conjugations, which makes the language an abugida

Ex: 
- Consonant+Consonant combination: 
క-  This is a basic consonant- Translates to "Ka"
క్క- This is a consonant conjugated with itself - Translates to "Kka"

- Vowel+ Consonant combination:
క- This is a basic consonant- Translates to "Ka"
కా- This is a consonant conjugated with a vowel - Translates to "Kaa"

Now, it's easier to see how 60 characters can evolve into 2032 unique character representations.  

PC: We also have monsters like this character "జ్ఞ" which crashed macs and iPhones sometime ago. Here's a fun video https://www.youtube.com/watch?v=HUE9mCN7sek


Source: https://en.wikipedia.org/wiki/Telugu_script

**Comment by rkcosmos** [comment]
Oh well, your language is probably even harder than Chinese. I'll see what I can do.

**Comment by rkcosmos** [comment]
By the way, more words are needed. Now number of characters is even more than words.

**Comment by Msrikrishna** [comment]
I am not sure exactly how the recognition algo works, but I thought the word list provides more dexterity to the recognition. Also what happens to the recognition if the word's not in the list? I am asking because it seems quite hard to get hands on the complex Telugu word compilations.

**Comment by rkcosmos** [comment]
They are used firstly when creating dataset for training. Generally more variation is better for avoiding overfitting. Secondly there are used for 'wordbeamsearch' decoding, this decoder is not working well right now but I hope it to be better in the future.

**Comment by Msrikrishna** [comment]
Thanks for the explanation! Since there is no publically available word database for my language, I am planning to scrape magazines, newspapers, websites and maybe use google translate a bit to generate a rich database, which could not only help this project but also other projects in the future. I Will update here as soon as I can. Cheers!

**Pull request merged**
